spring:
  datasource:
#    url: jdbc:mysql://59.110.167.53:3306/mymall_ums
    url: jdbc:mysql://192.168.112.100:3306/mymall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      max-lifetime: 50000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mymall-member

  session:
    store-type: redis
  redis:
    host: 192.168.112.100
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#  设置tableId注解为自增主键。默认是None
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
