spring:
  datasource:
#    url: jdbc:mysql://59.110.167.53:3306/mymall_pms
    url: jdbc:mysql://192.168.112.100:3306/mymall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      max-lifetime: 50000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4FzvCL76TNUueg6hv27b
      secret-key: 6sCJtLaYGrxlJ2E1zyGKWa4A6Nclce
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: mymall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
#    host: 59.110.167.53
    host: 192.168.112.100
    port: 6379

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#  设置tableId注解为自增主键。默认是None
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1   #此处有意写反,若在相关字段上有@TableLogic()注解，优先读注解的
      logic-not-delete-value: 0
#server:
#  port: 30002

logging:
  level:
    com.harbin.mymall: debug
feign:
  hystrix:
    enabled: false

easymall:
  thread:
    core: 20
    max-size: 200
    keep-alive-time: 10