spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mymall-cart
  redis:
    host: 192.168.112.100
    port: 6379
  thymeleaf:
    cache: false
server:
  port: 25000


easymall:
  thread:
    core: 20
    max-size: 200
    keep-alive-time: 10
